# replace default config

# multipass: true
# full: true

plugins:

  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2

  - removeDoctype
  - removeXMLProcInst
  - removeComments
  - removeMetadata
  - removeXMLNS: false
  - removeEditorsNSData
  - cleanupAttrs
  - inlineStyles
  - minifyStyles
  - convertStyleToAttrs
  - cleanupIDs: false
  - prefixIds
  - removeRasterImages
  - removeUselessDefs
  - cleanupNumericValues: false
  - cleanupListOfValues: false
  - convertColors
  - removeUnknownsAndDefaults
  - removeNonInheritableGroupAttrs
  - removeUselessStrokeAndFill
  - removeViewBox: false
  - cleanupEnableBackground
  - removeHiddenElems
  - removeEmptyText
  - convertShapeToPath
  - moveElemsAttrsToGroup
  - moveGroupAttrsToElems
  - collapseGroups: false
  - convertPathData: false
  - convertTransform
  - removeEmptyAttrs
  - removeEmptyContainers
  - mergePaths
  - removeUnusedNS
  - sortAttrs: false
  - removeTitle: false
  - removeDesc
  - removeDimensions
  - removeAttrs
  - removeElementsByAttr
  - addClassesToSVGElement
  - removeStyleElement: false
  - removeScriptElement: false
  - addAttributesToSVGElement

# configure the indent (default 4 spaces) used by `--pretty` here:
#
# @see https://github.com/svg/svgo/blob/master/lib/svgo/js2svg.js#L6 for more config options
#
js2svg:
  pretty: true
  indent: '  '
